---
title: "Lab_#7_Tyler"
author: "Tyler Cobian"
date: "11/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
Hi Kal Lai this is Tyler, this is the second half of the lab rank based tests.


```{r}
library(tidyverse)

kermit<-read_csv("kermit.csv")

kermit_hist<-ggplot(kermit, aes(x=Score.pre)) +
  geom_histogram()+
  facet_wrap(~Gender)

kermit_hist

```

Im going to be doing some rank based tests with the data. Thanks collabrator!

```{r}
# Is there a significant difference in pre talk kermit score for males and females

#This is unpaired data so we will be Mann-Whitney U test:
mwu_kermit<- kermit %>% 
  wilcox.test(Score.pre ~ Gender, data = .)
mwu_kermit


```



###COLLABORATOR
#is there a significant difference in Kermit ranks for pre talk and post talk scores(ignorning all other variables)

Null: no
Alternative

```{r}


wsr_kermit<- wilcox.test(kermit$Score.pre, kermit$Score.post, paired = TRUE)


wsr_kermit

##there is no significant difference in kermit rankings before and after the talk(summmary....)

```











